services:
  # PostgreSQL Database
  postgres:
    image: postgres:15-alpine
    container_name: docflow_postgres_dev
    environment:
      POSTGRES_DB: docflow
      POSTGRES_USER: docflow_user
      POSTGRES_PASSWORD: docflow_password
    volumes:
      - postgres_dev_data:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - "5432:5432"
    networks:
      - docflow_dev_network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U docflow_user -d docflow"]
      interval: 10s
      timeout: 5s
      retries: 5

  # FastAPI Backend (Development)
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: docflow_backend_dev
    environment:
      DATABASE_URL: postgresql+asyncpg://docflow_user:docflow_password@postgres:5432/docflow
      SECRET_KEY: development-secret-key
      ACCESS_TOKEN_EXPIRE_MINUTES: 30
    volumes:
      - ./backend:/app
      - uploads_dev_data:/app/uploads
    ports:
      - "8000:8000"
    networks:
      - docflow_dev_network
    depends_on:
      postgres:
        condition: service_healthy
    command: ["python", "start.py"]

  # React Frontend (Development)
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile.dev
    container_name: docflow_frontend_dev
    environment:
      - VITE_API_URL=http://localhost:8000
    volumes:
      - ./frontend:/app
      - /app/node_modules
    ports:
      - "3000:5173"
    networks:
      - docflow_dev_network
    depends_on:
      - backend
    healthcheck:
      test:
        [
          "CMD",
          "wget",
          "--no-verbose",
          "--tries=1",
          "--spider",
          "http://localhost:5173/",
        ]
      interval: 30s
      timeout: 10s
      retries: 3

  # Redis (Development)
  redis:
    image: redis:7-alpine
    container_name: docflow_redis_dev
    ports:
      - "6379:6379"
    networks:
      - docflow_dev_network

volumes:
  postgres_dev_data:
    driver: local
  uploads_dev_data:
    driver: local

networks:
  docflow_dev_network:
    driver: bridge
